spring:
  application:
    name: producer-demo
server:
  port: 8081

aws:
  key:
    id: id
    secret: secret

event-bus:
  enable: true
  region: ap-southeast-1
  account: 660209155792
  sns:
    endpoint: https://sns.ap-southeast-1.amazonaws.com
    topics:
      message-changed: arn:aws:sns:${event-bus.region}:${event-bus.account}:messageChanged.fifo