spring:
  application:
    name: consumer-demo
server:
  port: 8082

aws:
  key:
    id: id
    secret: secret

event-bus:
  enable: true
  region: ap-southeast-1
  account: 660209155792
  sqs:
    endpoint: https://sqs.ap-southeast-1.amazonaws.com
    queues:
      message-changed: messageChanged.fifo